# Generated by Django 3.1.6 on 2021-06-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog_app', '0004_auto_20210608_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='Coding', max_length=255, verbose_name='Category'),
        ),
    ]
