# Generated by Django 3.1.6 on 2021-06-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog_app', '0005_auto_20210610_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=255, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='My Bio', null=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='myblog_app/images/user.png', null=True, upload_to='images/profile/', verbose_name='Profile Picture'),
        ),
    ]
